### ISSUE TITLE
do-not-join-instance flag in RPL ext control option

### ISSUE THREAD

**Issue by nyrahul** [roll-wg/mopex#8]
Currently, the MOPex draft extends the RPL control options with certain flags to handle cases where the control option is not understood by the node:
J-flag: Join only as 6LN
C-flag: copy option as-is even if not understood
I-flag: Ignore message altogether.

We could have an option for the node to not join the network at all (not even as 6LN) if a control option is not understood.

**Comment by mcr** [comment]
Would the node reply in some way to say that it wasn't joining?

**Comment by nyrahul** [comment]
> Would the node reply in some way to say that it wasn't joining?

The node in this case will send NPDAO to clear it’s existing routes (assuming it has connected itself to the instance) before dropping off from the rpl instance. We can define a new rpl status value to signal that it is dropping off because of unsupported control option. 

In this way node has some way of reporting of it going off grid to the intermediate 6lr s and BR.

**Comment by mcr** [comment]
I'm not sure that we should have the "not join the network at all", (I could be convinced).  But, I wanted to know how it will send the NAK if it doesn't join the LLN :-)
